Could not import garmin_sync.py. Make sure it's in the same directory.
